package com.xtremis.daedo.wtdata.model.constants;

public enum Action {
  MATCH_LOADED, MATCH_START, ROUND_START, MATCH_TIME, MATCH_TIMEOUT, MATCH_RESUME, ROUND_END, MATCH_END, SCORE_HOME_PUNCH, SCORE_HOME_KICK, SCORE_HOME_TKICK, SCORE_HOME_HEAD, SCORE_HOME_THEAD, PENALTY_HOME, SCORE_AWAY_PUNCH, SCORE_AWAY_KICK, SCORE_AWAY_TKICK, SCORE_AWAY_HEAD, SCORE_AWAY_THEAD, PENALTY_AWAY, INVALIDATE_SCORE, ADJUST_SCORE, ADJUST_PENALTY, VR_HOME_REQUEST, VR_HOME_ACCEPTED, VR_HOME_REJECTED, VR_AWAY_REQUEST, VR_AWAY_ACCEPTED, VR_AWAY_REJECTED;
}
