ALTER TABLE TKS_MATCH_CONFIG
    ADD COLUMN CREATED_DATETIME DATETIME DEFAULT NOW();

ALTER TABLE TKS_MATCH_CONFIG
    ADD COLUMN LAST_UPDATE_DATETIME DATETIME DEFAULT NOW();

ALTER TABLE TKS_MATCH_CONFIG
    ADD COLUMN MATCH_STARTED BOOLEAN DEFAULT FALSE;
