-- AFEEGIM NOVES RULES PELS BOUNS POINTS

ALTER TABLE TKS_RULES
    ADD COLUMN BONUS_POINTS_ENABLED BOOLEAN DEFAULT 0;

ALTER TABLE TKS_RULES
    ADD COLUMN BONUS_POINTS_MIN_LEVEL INTEGER DEFAULT 45;

ALTER TABLE TKS_RULES
    ADD COLUMN BONUS_POINTS_POINTS INTEGER DEFAULT 2;

UPDATE TKS_RULES SET BONUS_POINTS_ENABLED = 0, BONUS_POINTS_MIN_LEVEL = 50, BONUS_POINTS_POINTS = 2;
