
ALTER TABLE TKS_RULES
    ADD COLUMN FORCE_MAX_GAMJOM BOOLEAN DEFAULT 0;

ALTER TABLE TKS_RULES
    ADD COLUMN MAX_GAMJOM_ALLOWED INTEGER DEFAULT 10;

UPDATE TKS_RULES SET FORCE_MAX_GAMJOM = 0, MAX_GAMJOM_ALLOWED = 10;
