ALTER TABLE TKS_RULES
    ALTER COLUMN MATCH_VICTORY_CRITERIA  VARCHAR(12) DEFAULT 'CONVENTIONAL' NOT NULL;

ALTER TABLE TKS_MATCH_CONFIG
    ALTER COLUMN MATCH_VICTORY_CRITERIA  VARCHAR(12) DEFAULT 'CONVENTIONAL' NOT NULL;

ALTER TABLE TKS_MATCH_LOG
    ALTER COLUMN MATCH_VICTORY_CRITERIA  VARCHAR(12) DEFAULT 'CONVENTIONAL' NOT NULL;

ALTER TABLE TKS_HISTO_MATCH_LOG
    ALTER COLUMN MATCH_VICTORY_CRITERIA  VARCHAR(12) DEFAULT 'CONVENTIONAL' NOT NULL;

UPDATE TKS_RULES SET MATCH_VICTORY_CRITERIA = 'CONVENTIONAL' WHERE MATCH_VICTORY_CRITERIA = 'BY_POINTS';
UPDATE TKS_RULES SET MATCH_VICTORY_CRITERIA = 'BESTOF3' WHERE MATCH_VICTORY_CRITERIA = 'BY_ROUNDS';

UPDATE TKS_MATCH_CONFIG SET MATCH_VICTORY_CRITERIA = 'CONVENTIONAL' WHERE MATCH_VICTORY_CRITERIA = 'BY_POINTS';
UPDATE TKS_MATCH_CONFIG SET MATCH_VICTORY_CRITERIA = 'BESTOF3' WHERE MATCH_VICTORY_CRITERIA = 'BY_ROUNDS';

UPDATE TKS_MATCH_LOG SET MATCH_VICTORY_CRITERIA = 'CONVENTIONAL' WHERE MATCH_VICTORY_CRITERIA = 'BY_POINTS';
UPDATE TKS_MATCH_LOG SET MATCH_VICTORY_CRITERIA = 'BESTOF3' WHERE MATCH_VICTORY_CRITERIA = 'BY_ROUNDS';

UPDATE TKS_HISTO_MATCH_LOG SET MATCH_VICTORY_CRITERIA = 'CONVENTIONAL' WHERE MATCH_VICTORY_CRITERIA = 'BY_POINTS';
UPDATE TKS_HISTO_MATCH_LOG SET MATCH_VICTORY_CRITERIA = 'BESTOF3' WHERE MATCH_VICTORY_CRITERIA = 'BY_ROUNDS';
