-- NetworkConfig
CREATE TABLE TKS_NETWORK_CONFIG
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	NETWORK_WAS_STARTED BOOLEAN,
	CHANNEL INTEGER,
	N_JUDGES INTEGER,
	JD_1_NODE_ID VARCHAR(20),
	JD_2_NODE_ID VARCHAR(20),
	JD_3_NODE_ID VARCHAR(20),
	HEAD_TP_ENABLED BOOLEAN,
	G1_HS_ENABLED BOOLEAN,
	G1_BS_ENABLED BOOLEAN,
	G1_BB_NODE_ID VARCHAR(20),
	G1_HB_NODE_ID VARCHAR(20),
	G1_BR_NODE_ID VARCHAR(20),
	G1_HR_NODE_ID VARCHAR(20),
	GROUP2_ENABLED BOOLEAN,
	G2_HS_ENABLED BOOLEAN,
	G2_BS_ENABLED BOOLEAN,
	G2_BB_NODE_ID VARCHAR(20),
	G2_HB_NODE_ID VARCHAR(20),
	G2_BR_NODE_ID VARCHAR(20),
	G2_HR_NODE_ID VARCHAR(20),
	N_GROUPS INTEGER DEFAULT 1,
	G3_HS_ENABLED BOOLEAN,
	G3_BS_ENABLED BOOLEAN,
	G3_BB_NODE_ID VARCHAR(20),
	G3_HB_NODE_ID VARCHAR(20),
	G3_BR_NODE_ID VARCHAR(20),
	G3_HR_NODE_ID VARCHAR(20),
	G4_HS_ENABLED BOOLEAN,
	G4_BS_ENABLED BOOLEAN,
	G4_BB_NODE_ID VARCHAR(20),
	G4_HB_NODE_ID VARCHAR(20),
	G4_BR_NODE_ID VARCHAR(20),
	G4_HR_NODE_ID VARCHAR(20),
	G5_HS_ENABLED BOOLEAN,
	G5_BS_ENABLED BOOLEAN,
	G5_BB_NODE_ID VARCHAR(20),
	G5_HB_NODE_ID VARCHAR(20),
	G5_BR_NODE_ID VARCHAR(20),
	G5_HR_NODE_ID VARCHAR(20),
	G6_HS_ENABLED BOOLEAN,
	G6_BS_ENABLED BOOLEAN,
	G6_BB_NODE_ID VARCHAR(20),
	G6_HB_NODE_ID VARCHAR(20),
	G6_BR_NODE_ID VARCHAR(20),
	G6_HR_NODE_ID VARCHAR(20)
);

-- Rules
CREATE TABLE TKS_RULES
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	BODY_POINTS INTEGER,
	HEAD_POINTS INTEGER,
	PUNCH_POINTS INTEGER,
	BODY_TECH_POINTS INTEGER,
	HEAD_TECH_POINTS INTEGER,
	OVERTIME_POINTS INTEGER,
	CELLING_SCORE INTEGER,
	DIFFERENCIAL_SCORE INTEGER,
	NEAR_MISS_LEVEL INTEGER,
	ROUNDS INTEGER,
	ROUND_TIME VARCHAR(5),
	KYESHI_TIME VARCHAR(5),
	REST_TIME VARCHAR(5),
	GOLDENPOINT_ENABLED BOOLEAN,
	GOLDENPOINT_TIME VARCHAR(5),
	PARA_SPINNING_KICK_POINTS INTEGER DEFAULT 2 NOT NULL,
	PARA_TURNING_KICK_POINTS INTEGER DEFAULT 1 NOT NULL,
	ALL_MATCH_PARA BOOLEAN DEFAULT FALSE,
	OVERTIME_PENALTIES INTEGER DEFAULT 2 NOT NULL,
	MATCH_VICTORY_CRITERIA VARCHAR(10) DEFAULT 'BY_POINTS' NOT NULL,
	GAMJEOM_SHOW_POINTS_ON_GOLDENPOINT BOOLEAN DEFAULT FALSE
);

-- Sound Config
CREATE TABLE TKS_SOUND_CONFIG
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	BET_ENABLED BOOLEAN,
	BET_VOLUME VARCHAR(6),
	BET_SOUND VARCHAR(255),
	BET_BEFORE_SECONDS INTEGER,
	BSR_ENABLED BOOLEAN,
	BSR_VOLUME VARCHAR(6),
	BSR_SOUND VARCHAR(255),
	BSR_BEFORE_SECONDS INTEGER,
	EOT_ENABLED BOOLEAN,
	EOT_VOLUME VARCHAR(6),
	EOT_SOUND VARCHAR(255),
	WBH_ENABLED BOOLEAN,
	WBH_VOLUME VARCHAR(6),
	WBH_SOUND VARCHAR(255),
	WHH_ENABLED BOOLEAN,
	WHH_VOLUME VARCHAR(6),
	WHH_SOUND VARCHAR(255),
	WKG_ENABLED BOOLEAN,
	WKG_VOLUME VARCHAR(6),
	WKG_SOUND VARCHAR(255),
	WGJ_ENABLED BOOLEAN,
	WGJ_VOLUME VARCHAR(6),
	WGJ_SOUND VARCHAR(255),
	TM_ENABLED BOOLEAN,
	TM_VOLUME VARCHAR(6),
	TM_SOUND VARCHAR(255)
);

-- External Config
CREATE TABLE TKS_EXTERNAL_CONFIG
(
	ID VARCHAR(45) NOT NULL PRIMARY KEY,
	VERSION INTEGER,
	VM_URL VARCHAR(510),
	EXT_SCOREBOARD_BLUEONLEFT BOOLEAN,
	EXT_SCOREBOARD_RESOLUTION VARCHAR(5),
	RTB_IP VARCHAR(15),
	RTB_PORT INTEGER,
	RTB_RING_NUM VARCHAR(3),
	MATCH_LOG_OUTPUT_DIRECTORY CLOB DEFAULT '' NOT NULL,
	VM_RING_NUMBER VARCHAR(75),
	WT_OVR_URL VARCHAR(510),
	WT_OVR_X_API_KEY VARCHAR(510),
	WT_OVR_MAT INTEGER,
	WT_OVR_UDP_IP VARCHAR(15),
	WT_OVR_UDP_LISTEN_PORT INTEGER,
	WT_OVR_UDP_WRITE_PORT INTEGER
);

-- Event Listeners URL's
CREATE TABLE TKS_EVENT_LISTENER_URLS
(
	EXTERNAL_CONFIG_ID VARCHAR(45),
	LISTENER_URL VARCHAR(510)
);

-- Node Event Listener url's
CREATE TABLE TKS_NODE_EVENT_LISTENER_URLS
(
	EXTERNAL_CONFIG_ID VARCHAR(45),
	LISTENER_URL VARCHAR(510)
);

-- Udp Event Listeners
CREATE TABLE TKS_UDP_EVENT_LISTENER
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	LISTENER_IP VARCHAR(15),
	LISTENER_PORT INTEGER
);

