-- Phase
CREATE TABLE TKS_PHASE
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	NAME VARCHAR(400),
	ABBREVIATION VARCHAR(10) DEFAULT 'NULL' NOT NULL
);

-- Referee
CREATE TABLE TKS_REFEREE
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	LICENSE_NUMBER VARCHAR(400),
	SCOREBOARD_NAME VARCHAR(400),
	COUNTRY VARCHAR(400)
);

-- Sub Category
CREATE TABLE TKS_SUBCATEGORY
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	NAME VARCHAR(400)
);

-- Category
CREATE TABLE TKS_CATEGORY
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	NAME VARCHAR(400),
	GENDER VARCHAR(10),
	SUBCATEGORY_ID VARCHAR(45),
	BODY_LEVEL INTEGER,
	HEAD_LEVEL INTEGER
);

-- Flag
CREATE TABLE TKS_ATHLETE
(
	ID VARCHAR(45) NOT NULL PRIMARY KEY,
	VERSION INTEGER,
	WF_ID VARCHAR(25),
	FLAG_ID VARCHAR(45),
	OVR_INTERNAL_ID VARCHAR(50),
	SCOREBOARD_NAME VARCHAR(400),
	GIVEN_NAME VARCHAR(400),
	FAMILY_NAME VARCHAR(400),
	PASSPORT_GIVEN_NAME VARCHAR (400),
	PASSPORT_FAMILY_NAME VARCHAR (400),
	PREFERRED_GIVEN_NAME VARCHAR (400),
	PREFERRED_FAMILY_NAME VARCHAR (400),
	PRINT_NAME VARCHAR (400),
	PRINT_INITIAL_NAME VARCHAR (400),
	TV_NAME VARCHAR (400),
	TV_INITIAL_NAME VARCHAR (400),
	GENDER VARCHAR(10),
	BIRTH_DATE DATE,
	COMPETITOR_TYPE VARCHAR(1) DEFAULT 'A',
	RANK INT DEFAULT 0,
	SEED INT DEFAULT 0
);

-- Athlete
CREATE TABLE TKS_FLAG
(
	ID VARCHAR(45) NOT NULL PRIMARY KEY,
	VERSION INTEGER,
	NAME VARCHAR(400),
	ABBREVIATION VARCHAR(15),
	FLAG_IMAGE_PATH VARCHAR(510),
	SHOW_NAME BOOLEAN DEFAULT 0
);

CREATE INDEX I_TKS_FLAG_ABBR
	ON TKS_FLAG (ABBREVIATION);


ALTER TABLE TKS_ATHLETE ADD CONSTRAINT WTF_ID_UNIQUE UNIQUE (WF_ID);

-- Differential Score
CREATE TABLE TKS_DIFFERENTIAL_SCORE_DEF
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	PHASE_ID VARCHAR(45) NOT NULL,
	SUBCATEGORY_ID VARCHAR(45) NOT NULL,
	THE_VALUE INTEGER DEFAULT 0,
	CONSTRAINT DIFFERENTIAL_SCORE_DEF_UQI
		UNIQUE (PHASE_ID, SUBCATEGORY_ID)
);

-- Match Config
CREATE TABLE TKS_MATCH_CONFIG
(
	ID VARCHAR(45) NOT NULL	PRIMARY KEY,
	VERSION INTEGER,
	SENSORS_GROUP VARCHAR(5),
	MATCH_NUMBER VARCHAR(15) UNIQUE,
	PHASE_ID VARCHAR(45),
	CATEGORY_ID VARCHAR(45),
	BLUE_ATHLETE_ID VARCHAR(45),
	BLUE_VIDEO_QUOTA INTEGER,
	RED_ATHLETE_ID VARCHAR(45),
	RED_VIDEO_QUOTA INTEGER,
	ROUNDS INTEGER,
	ROUND_TIME VARCHAR(5),
	KYESHI_TIME VARCHAR(5),
	REST_TIME VARCHAR(5),
	GOLDENPOINT_ENABLED BOOLEAN,
	GOLDENPOINT_TIME VARCHAR(5),
	VMS_MATCH_INTERNAL_ID VARCHAR(255) DEFAULT 'NULL',
	IS_PARATKD_MATCH BOOLEAN DEFAULT FALSE,
	DIFFERENCIAL_SCORE INTEGER DEFAULT 20 NOT NULL,
	MAX_GAM_JEOMS INTEGER,
	IS_WT_DM BOOLEAN DEFAULT FALSE,
	REFEREE_CR_ID VARCHAR(45) DEFAULT 'NULL',
	REFEREE_TA_ID VARCHAR(45) DEFAULT 'NULL',
	REFEREE_RJ_ID VARCHAR(45) DEFAULT 'NULL',
	REFEREE_J1_ID VARCHAR(45) DEFAULT 'NULL',
	REFEREE_J2_ID VARCHAR(45) DEFAULT 'NULL',
	REFEREE_J3_ID VARCHAR(45) DEFAULT 'NULL'
);