package com.xtremis.daedo.tkstrike.om;

public enum MatchStatusId {
  NETWORK_ERROR, NOT_READY, WAITING_4_MATCH, WAITING_4_START_ROUND, WAITING_4_START_GOLDENPOINT, ROUND_WORKING, ROUND_PAUSED, ROUND_PARA_TIMEOUT_WORKING, ROUND_KYESHI, ROUND_FINISHED, ROUND_IN_RESTTIME, ROUND_IN_GOLDENPOINT, ROUND_GOLDENPOINT_FINISHED, MATCH_NEEDS_CONFIRM_FINAL_DECISION, MATCH_FINISHED;
}
