package com.xtremis.daedo.tkstrike.om;

public enum AppStatusId {
  NETWORK_NOT_CONFIGURED, NETWORK_ERROR, NETWORK_CONFIGURED, NETWORK_RECOVERED, MATCH_CONFIGURED, HT_JUDGES_OK, HT_ATHLETES_OK, READY_FOR_MATCH, MATCH_WORKING, ROUND_PAUSED, ROUND_KYESHI, ROUND_FINISHED, MATCH_FINISHED;
}
